const Products = require('./server/db/models/foodProducts');
const db = require('./server/db')

// name brand price photo totalSales category stars tags

const ourSeed = [
  {
    name: 'Gowanus Ice Cream',
    brand: 'Ample Hills',
    price: 7.99,
    photo: '/photography/ampleHills.png',
    totalSales: 5,
    category: 'Ice Cream',
    stars: 5,
    tags: ['Ice Cream', 'Dessert', 'Small-Batch']
  },

  {
    name: 'Earl Grey Ice Cream',
    brand: 'Van Leeuwen',
    price: 7.99,
    photo: '/photography/vanleeuwen.jpg',
    totalSales: 7,
    category: 'Ice Cream',
    stars: 3.0,
    tags: ['Ice Cream', 'Small Batch', 'Organic', 'Brooklyn']
  },
  {
    name: '4-pack patty',
    brand: 'Impossible Burger',
    price: 14.99,
    photo: '/photography/burger.jpg',
    totalSales: 8,
    category: 'Vegetarian',
    stars: 4.0,
    tags: ['Burger', 'Vegan', 'Health', 'Organic']
  },
  {
    name: '6-pack patty',
    brand: 'Beyond Meat',
    price: 14.99,
    photo: '/photography/burger.jpg',
    totalSales: 15,
    category: 'Vegetarian',
    stars: 5.0,
    tags: ['Burger', 'Vegan', 'Health', 'Meat']
  },
  {
    name: 'Whole Free-Range Bird',
    brand: 'PurBird',
    price: 19.99,
    photo: '/photography/chicken.jpg',
    totalSales: 25,
    category: 'Chicken',
    stars: 4.5,
    tags: ['Chicken', 'Poultry', 'Free Range', 'Organic']
  },
  {
    name: 'Cara Cara Oranges',
    brand: 'United Fruit Company',
    price: 2.0,
    photo: '/photography/oranges.jpg',
    totalSales: 40,
    category: 'Fruit',
    stars: 5.0,
    tags: ['Fruit', 'Orange', 'Organic', 'Citrus']
  },
  {
    name: 'Kiwi',
    brand: 'New Zealand Fruits',
    price: 1.99,
    photo: '/photography/kiwi.jpg',
    totalSales: 30,
    category: 'Fruit',
    stars: 4.0,
    tags: ['Fruit', 'Exotic', 'Green']
  },
  {
    name: '12oz Kale',
    brand: 'NY Greens',
    price: 5.99,
    photo: '/photography/kale.jpg',
    totalSales: 25,
    category: 'Greens',
    stars: 4.2,
    tags: ['Kale', 'Lettuce', 'Organic', 'Green', 'Health', 'Cruciferous']
  },
  {
    name: '3oz Sardines',
    brand: 'Bar Harbor',
    price: 3.99,
    photo: '/photography/sardines.jpg',
    totalSales: 30,
    category: 'Seafood',
    stars: 4.8,
    tags: ['Seafood', 'Sustainable', 'Canned', 'Fish']
  },
  {
    name: 'Scottish Salmon',
    brand: 'Greenpoint Fish Co',
    price: 19.99,
    photo: '/photography/salmon.jpg',
    totalSales: 21,
    category: 'Seafood',
    stars: 5.0,
    tags: ['Seafood', 'Farmed', 'Fresh', 'Fish']
  },
  {
    name: 'RockFish',
    brand: 'Greenpoint Fish Co',
    price: 14.99,
    photo: '/photography/rockfish.jpg',
    totalSales: 4,
    category: 'Seafood',
    stars: 5.0,
    tags: ['Seafood', 'Farmed', 'Fish', 'Sustainable']
  },
  {
    name: '12oz Arugula',
    brand: 'NY Greens',
    price: 4.99,
    photo: '/photography/arugula.jpg',
    totalSales: 40,
    category: 'Greens',
    stars: 5.0,
    tags: ['Green', 'Kale', 'Lettuce', 'Healthy', 'Organic']
  },
  {
    name: 'Tangelo',
    brand: 'Tangelo Co',
    price: 2.99,
    photo: '/photography/peeled-and-whole-tangelo.jpg',
    totalSales: 4,
    category: 'Fruit',
    stars: 5.0,
    tags: ['Fruit', 'Healthy', 'Sustainable']
  },
  {
    name: 'Lime Tortilla Chips',
    brand: 'Lime Tortilla Chips Co',
    price: 3.99,
    photo: '/photography/tortilla-chips.jpg',
    totalSales: 4,
    category: 'snacks',
    stars: 5.0,
    tags: ['snacks', 'exotic']
  },
  {
    name: 'Organic Avocado',
    brand: 'Avocado Co',
    price: 2.99,
    photo: '/photography/avocado.jpg',
    totalSales: 4,
    category: 'Vegetables',
    stars: 5.0,
    tags: ['Vegetables', 'Healthy', 'Organic', 'Green']
  },
  {
    name: 'Tempeh',
    brand: 'Beyond Meat',
    price: 4.99,
    photo: '/photography/kale.jpg',
    totalSales: 41,
    category: 'Vegetarian',
    stars: 5.0,
    tags: ['Vegetarian', 'Soy', 'Healthy', 'Organic']
  },
  {
    name: 'Firm Tofu',
    brand: 'House Foods',
    price: 3.99,
    photo: '/photography/tofu.jpg',
    totalSales: 87,
    category: 'Vegetarian',
    stars: 5.0,
    tags: ['Vegetarian', 'Soy', 'Healthy', 'Organic']
  },
  {
    name: 'Duck Breast',
    brand: 'Purbird',
    price: 12.99,
    photo: '/photography/chicken.jpg',
    totalSales: 14,
    category: 'Poultry',
    stars: 5.0,
    tags: ['Poultry', 'Meat', 'Free Range', 'Organic']
  },
  {
    name: 'Miso',
    brand: 'House Foods',
    price: 7.99,
    photo: '/photography/tofu.jpg',
    totalSales: 14,
    category: 'Condiments',
    stars: 5.0,
    tags: ['Soy', 'Exotic', 'Japanese', 'Organic']
  },
  {
    name: 'Green Beans',
    brand: 'New Jersey Farms',
    price: 4.99,
    photo: '/photography/green.jpg',
    totalSales: 24,
    category: 'Vegetables',
    stars: 5.0,
    tags: ['Green', 'Vegetables', 'Produce', 'Organic']
  },
  {
    name: 'Green Onion',
    brand: 'NY Greens',
    price: 3.99,
    photo: '/photography/green.jpg',
    totalSales: 88,
    category: 'Vegetables',
    stars: 5.0,
    tags: ['Green', 'Vegetables', 'Produce', 'Organic', 'Onion']
  },
  {
    name: 'Green Bell Pepper',
    brand: 'New Jersey Farms',
    price: 2.99,
    photo: '/photography/green.jpg',
    totalSales: 101,
    category: 'Vegetables',
    stars: 5.0,
    tags: ['Green', 'Vegetables', 'Produce', 'Organic', 'Onion']
  },
  {
    name: 'Pistachio Ice Cream',
    brand: 'Van Leeuwen',
    price: 7.99,
    photo: '/photography/vanleeuwen.jpg',
    totalSales: 11,
    category: 'Ice Cream',
    stars: 5.0,
    tags: ['Green', 'Dessert', 'Ice Cream', 'Local']
  },
  {
    name: '100% Cocoa Bar',
    brand: 'Antidote',
    price: 9.99,
    totalSales: 98,
    category: 'Chocolate',
    stars: 5.0,
    tags: ['Organic', 'Dessert', 'Chocolate', 'Local', 'Vegan', 'snacks']
  },
  {
    name: 'Chocolate Pudding',
    brand: 'Jell-o',
    price: 3.99,
    photo: '/photography/ampleHills.png',
    totalSales: 80,
    category: 'Dessert',
    stars: 4.0,
    tags: ['Dessert', 'Chocolate', 'snacks']
  },
  {
    name: 'Chia Pudding',
    brand: 'GT',
    price: 5.99,
    photo: '/photography/chia.png',
    totalSales: 40,
    category: 'Dessert',
    stars: 4.0,
    tags: ['Dessert', 'Organic', 'Healthy', 'SuperFood', 'Vegan']
  },
  {
    name: 'Fruit Cup',
    brand: 'New Jersey Farms',
    price: 5.99,
    photo: '/photography/chia.png',
    totalSales: 48,
    category: 'Fruit',
    stars: 4.0,
    tags: ['Dessert', 'Fruit', 'Healthy', 'Kiwi', 'Melon', 'Vegan']
  },
  {
    name: 'Green Papaya',
    brand: 'Thailand',
    price: 5.99,
    photo: '/photography/honeydew.png',
    totalSales: 4,
    category: 'Fruit',
    stars: 4.0,
    tags: ['Exotic', 'Fruit', 'Melon']
  },
  {
    name: 'Papaya',
    brand: 'New Jersey Farms',
    price: 5.99,
    photo: '/photography/cantaloupe.jpg',
    totalSales: 4,
    category: 'Fruit',
    stars: 4.0,
    tags: ['Exotic', 'Fruit', 'Melon', 'Orange']
  },
  {
    name: 'Cantaloupe',
    brand: 'New Jersey Farms',
    price: 4.99,
    photo: '/photography/cantaloupe.jpg',
    totalSales: 46,
    category: 'Fruit',
    stars: 4.0,
    tags: ['Fruit', 'Melon', 'Orange']
  },
  {
    name: 'HoneyDew',
    brand: 'New Jersey Farms',
    price: 5.99,
    photo: '/photography/honeydew.png',
    totalSales: 46,
    category: 'Fruit',
    stars: 4.0,
    tags: ['Fruit', 'Melon', 'Green', 'Healthy']
  },
  {
    name: 'Earl Grey Tea',
    brand: 'MemTea',
    price: 5.99,
    photo: '/photography/tea.jpg',
    totalSales: 46,
    category: 'Tea',
    stars: 4.0,
    tags: ['tea', 'bergamont', 'black tea', 'hot', 'citrus', 'caffeine']
  },
  {
    name: 'Pu-Erh Tea',
    brand: 'Koh Importers',
    price: 25.99,
    photo: '/photography/tea.jpg',
    totalSales: 46,
    category: 'Tea',
    stars: 4.0,
    tags: ['tea', 'fermented', 'black tea', 'hot', 'bitter', 'caffeine','chocolate']
  },
  {
    name: 'Green Tea',
    brand: 'Tao Jones Industries',
    price: 15.95,
    photo: '/photography/tea.jpg',
    totalSales: 46,
    category: 'Tea',
    stars: 4.0,
    tags: ['tea', 'green', 'relaxing', 'hot', 'caffeine']
  },
{
  name: 'Halibut',
  brand: 'United Fishmongeries',
  price: 19.99,
  photo: '/photography/salmon.jpg',
  totalSales: 46,
  category: 'Seafood',
  stars: 4.0,
  tags: ['fish', 'fresh', 'mercury', 'seafood', 'unethical']
},
{name: 'Trail Mix',
  brand: 'Cucumber',
  price: 7.99,
  totalSales: 46,
  category: 'Snacks',
  stars: 4.0,
  tags: ['nuts', 'raisins', 'chocolate', 'filling', 'peanuts', 'healthy']
},
{name: 'Silken Tofu',
  brand: 'House Foods',
  price: 1.99,
  photo: '/photography/tofu.jpg',
  totalSales: 46,
  category: 'Vegetarian',
  stars: 4.0,
  tags: ['tofu', 'silken', 'soft', 'soy', 'protein', 'asian']
},
  {name: 'Broccoli Rabe',
  brand: 'Happy Family Distributors',
  price: 3.99,
  photo: '/photography/kale.jpg',
  totalSales: 46,
  category: 'Vegetarian',
  stars: 4.0,
  tags: ['broccoli', 'rabe', 'bitter', 'healthy']
  },
  {name: 'Baby Bok Choy',
  brand: 'Chaebol International',
  price: 3.99,
  photo: '/photography/arugula.jpg',
  totalSales: 46,
  category: 'Vegetarian',
  stars: 4.0,
  tags: ['bok choy', 'cabbage', 'baby', 'healthy', 'asian', 'green']
  },
  {name: 'Nopales',
  brand: 'JuanMart',
  price: 3.99,
  photo: '/photography/kale.jpg',
  totalSales: 46,
  category: 'Vegetarian',
  stars: 4.0,
  tags: ['catcus', 'cacti', 'Mexican', 'healthy', 'green']
  },
  {name: 'Green Lentils',
  brand: 'Charles Lentejas',
  price: 4.99,
  photo: '/photography/lentil.jpg',
  totalSales: 46,
  category: 'Vegetarian',
  stars: 4.0,
  tags: ['lentils', 'protein', 'green', 'healthy']
  },
  {name: 'Beluga Lentils',
  brand: 'Stoianova Farms',
  price: 8.99,
  photo: '/photography/lentil.jpg',
  totalSales: 46,
  category: 'Vegetarian',
  stars: 4.0,
  tags: ['lentils', 'protein', 'black', 'healthy', 'dal', 'doll']
  },
  {name: 'Rainbow Chard',
  brand: 'Kermit Driscoll Farms',
  price: 3.99,
  photo: '/photography/kale.jpg',
  totalSales: 46,
  category: 'Vegetarian',
  stars: 4.0,
  tags: ['chard', 'swiss', 'bitter', 'healthy', 'green', 'vegan']
  },
  {name: 'Mangosteen',
  brand: 'Cocos Locos Etc.',
  price: 6.99,
  totalSales: 46,
  category: 'Fruit',
  stars: 4.0,
  tags: ['sweet', 'seed', 'red', 'healthy', 'fruit']
  },
  {name: 'Goji Berry',
  brand: 'Jujubees',
  price: 5.99,
  photo: '/photography/berry.jpg',
  totalSales: 46,
  category: 'Fruit',
  stars: 4.0,
  tags: ['berry', 'red', 'dry', 'healthy']
  },
  {name: 'Steel Cut Oatmeal',
  brand: 'Bob\'s Red Mill',
  price: 3.99,
  photo: '/photography/chia.png',
  totalSales: 46,
  category: 'Grain',
  stars: 4.0,
  tags: ['fiber', 'breakfast', 'gruel', 'healthy', 'grain', 'dry']
  },
  {name: 'Couscous',
  brand: 'TaGine',
  price: 1.99,
  photo: '/photography/pasta.jpg',
  totalSales: 46,
  category: 'Grain',
  stars: 4.0,
  tags: [ 'exotic', 'carbohydrate', 'healthy', 'grain', 'pasta']
  },
  {name: 'Orecchiette',
  brand: 'Mama Tia',
  price: 2.99,
  photo: '/photography/pasta.jpg',
  totalSales: 46,
  category: 'Grain',
  stars: 4.0,
  tags: ['grain', 'semolina', 'carbohydrate', 'healthy', 'pasta']
  },
  {name: 'Truffle Oil',
  brand: 'GoldStandard',
  price: 32.99,
  photo: '/photography/oliveoil.jpg',
  totalSales: 46,
  category: 'Oil',
  stars: 4.0,
  tags: ['oil', 'flavor', 'expensive', 'condiment']
  },
  {name: 'Olive Oil',
  brand: 'Our House Foods',
  price: 12.99,
  photo: '/photography/oliveoil.jpg',
  totalSales: 46,
  category: 'Oil',
  stars: 4.0,
  tags: ['olive', 'oil', 'lipid', 'grease', 'organic', 'condiment']
  },
  {name: 'Hot Sauce',
  brand: 'Pain 100',
  price: 2.99,
  photo: '/photography/hotsauce.jpg',
  totalSales: 46,
  category: 'Condiment',
  stars: 4.0,
  tags: ['spicy', 'brooklyn', 'red', 'acidic', 'flavor','pepper', 'mango']
  },
  {name: 'Red Ale',
  brand: 'Wheat Sickle',
  price: 13.99,
  photo: '/photography/redbeer.jpg',
  totalSales: 46,
  category: 'Alcohol',
  stars: 4.0,
  tags: ['alcohol', 'red', 'wheat', 'malt', 'craft','beer']
  },
  {name: 'Sour Ale',
  brand: 'Sewer Rats Brewing Co',
  price: 12.99,
  photo: '/photography/redbeer.jpg',
  totalSales: 46,
  category: 'Alcohol',
  stars: 4.0,
  tags: ['alcohol', 'brooklyn', 'sour', 'wheat', 'local', 'craft','beer']
  },
  {name: 'Gowanus Beer',
  brand: 'Fetid Waters',
  price: 14.99,
  photo: '/photography/redbeer.jpg',
  totalSales: 46,
  category: 'Alcohol',
  stars: 4.0,
  tags: ['alcohol', 'brooklyn', 'wheat', 'malt', 'craft','beer']
  },
  {name: 'Chocolate Stout',
  brand: 'Fundamental Brewery',
  price: 12.99,
  photo: '/photography/stout.jpg',
  totalSales: 46,
  category: 'Alcohol',
  stars: 4.0,
  tags: ['alcohol', 'chocolate', 'wheat', 'malt', 'craft','beer']
  },
  {name: 'Chocolate Chip Cookies',
  brand: 'A Museum of Modern Art in London',
  price: 6.99,
  photo: '/photography/cake.jpg',
  totalSales: 46,
  category: 'Dessert',
  stars: 4.0,
  tags: ['cookie', 'chocolate', 'baked', 'snacks']
  },
  {name: 'Sponge',
  brand: 'Celt-Brite',
  price: 3.99,
  totalSales: 46,
  category: 'Household',
  stars: 4.0,
  tags: ['sponge', 'cleaning', 'scrubbing', 'scouring', 'home', 'kitchen']
  },
  {name: 'Vitamin Q',
  brand: 'The Vitamen',
  price: 22.99,
  totalSales: 46,
  category: 'Supplement',
  stars: 4.0,
  tags: ['healthy']
  },
  {name: 'Canned Tomatoes',
  brand: 'San Marzano',
  price: 2.99,
  photo: '/photography/tomato.jpg',
  totalSales: 46,
  category: 'Vegetable',
  stars: 4.0,
  tags: ['tomato', 'red', 'canned', 'sauce']
  },
  {name: 'Tomatillo',
  brand: 'Naturist',
  price: 4.99,
  photo: '/photography/tomato.jpg',
  totalSales: 46,
  category: 'Vegetable',
  stars: 4.0,
  tags: ['green', 'tomato', 'chilaquiles', 'healthy']
  },
  {name: 'Russian Dressing',
  brand: 'Soya Etc',
  price: 6.99,
  totalSales: 46,
  category: 'Condiment',
  stars: 4.0,
  tags: ['cream', 'russian', 'salad', 'dressing']
  },
  {
    name: 'Wheatberries',
  brand: 'Dimes Deli',
  price: 6.99,
  photo: '/photography/lentil.jpg',
  totalSales: 49,
  category: 'Grain',
  stars: 4.0,
  tags: ['grain', 'carbohydrate', 'salad', 'pasta', 'fiber']
  },
  {
    name: 'Blackberries',
  brand: 'Cucumber Farms',
  price: 4.99,
  photo: '/photography/berry.jpg',
  totalSales: 80,
  category: 'Fruit',
  stars: 4.0,
  tags: ['fruit', 'berry', 'organic', 'black']
  },
  {
    name: 'Sour Cherry',
  brand: 'Cucumber Farms',
  price: 7.99,
  photo: '/photography/berry.jpg',
  totalSales: 98,
  category: 'Fruit',
  stars: 4.0,
  tags: ['fruit', 'berry', 'organic', 'sour', 'red']
  },
  {
    name: 'Black Striped Bass',
  brand: 'Greenpoint Fish',
  price: 17.99,
  totalSales: 8,
  category: 'Seafood',
  stars: 4.0,
  tags: ['fish', 'seafood', 'organic', 'atlantic', 'fresh']
  },
  {
    name: 'Squid Ink Pasta',
  brand: 'Nuestra Cosa',
  price: 7.99,
  photo: '/photography/pasta.jpg',
  totalSales: 18,
  category: 'Pasta',
  stars: 4.0,
  tags: ['grain', 'seafood', 'black', 'local', 'fresh']
  },
  {
    name: 'Matcha Tea',
  brand: 'Tea Cow',
  price: 7.99,
  photo: '/photography/tea.jpg',
  totalSales: 18,
  category: 'Tea',
  stars: 4.0,
  tags: ['exotic', 'tea', 'green', 'organic', 'asian']
  },
  {
    name: 'Jasmine Green Tea',
  brand: 'Tea Cow',
  price: 5.99,
  photo: '/photography/tea.jpg',
  totalSales: 18,
  category: 'Tea',
  stars: 4.0,
  tags: ['exotic', 'tea', 'green', 'organic', 'asian']
  },
  {
    name: 'Cranberries',
  brand: 'New Jersey Farms',
  price: 5.99,
  photo: '/photography/berry.jpg',
  totalSales: 18,
  category: 'Fruit',
  stars: 4.0,
  tags: ['fruit', 'berry', 'red', 'organic', 'bitter']
  },
  {
    name: 'Rasberries',
  brand: 'New Jersey Farms',
  price: 5.99,
  photo: '/photography/berry.jpg',
  totalSales: 18,
  category: 'Fruit',
  stars: 4.0,
  tags: ['fruit', 'berry', 'red', 'organic', 'sweet']
  },
  {
    name: 'Strawberries',
  brand: 'New Jersey Farms',
  price: 5.99,
  photo: '/photography/berry.jpg',
  totalSales: 18,
  category: 'Fruit',
  stars: 4.0,
  tags: ['fruit', 'berry', 'red', 'organic', 'sweet']
  },
  {
    name: 'Bitter Melon',
  brand: 'New Jersey Farms',
  price: 5.99,
  photo: '/photography/honeydew.png',
  totalSales: 18,
  category: 'Vegetable',
  stars: 4.0,
  tags: ['fruit', 'vegan', 'green', 'asian', 'bitter']
  },
  {
    name: 'Tupelo Honey',
  brand: 'Sweet Bee',
  price: 5.99,
  totalSales: 18,
  category: 'Condiments',
  stars: 4.0,
  tags: ['dessert', 'condiment', 'vegetarian', 'organic', 'sweet', 'honey', 'local']
  },
  {name: 'Sponge Cake',
  brand: 'Gather',
  price: 7.99,
  photo: '/photography/cake.jpg',
  totalSales: 46,
  category: 'Dessert',
  stars: 4.0,
  tags: ['dessert', 'sweet', 'cake']
  },
  {name: 'Coconut Ash Ice Cream',
  brand: 'Van Leeuwen',
  price: 7.99,
  photo: '/photography/vanleeuwen.jpg',
  totalSales: 46,
  category: 'Ice Cream',
  stars: 4.0,
  tags: ['dessert', 'ice cream', 'coconut','black', 'brooklyn']
  },
  {name: 'Chocolate Chunk Ice Cream',
  brand: 'Ample Hills',
  price: 7.99,
  photo: '/photography/ampleHills.png',
  totalSales: 46,
  category: 'Ice Cream',
  stars: 4.0,
  tags: ['dessert', 'ice cream', 'chocolate','local', 'brooklyn', 'sweet']
  },
  {name: 'Coconut',
  brand: 'New Jersey Farms',
  price: 7.99,
  photo: '/photography/coconut.jpg',
  totalSales: 46,
  category: 'Fruit',
  stars: 4.0,
  tags: ['Exotic', 'Fruit', 'dessert','healthy']
  },
  {name: 'Coconut Oil',
  brand: 'Nuestra Casa',
  price: 7.99,
  photo: '/photography/oliveoil.jpg',
  totalSales: 46,
  category: 'Oil',
  stars: 4.0,
  tags: ['Exotic', 'Oil', 'organic','healthy']
  },
  {name: 'Kombucha',
  brand: 'GT',
  price: 4.99,
  photo: '/photography/kombucha.jpg',
  totalSales: 46,
  category: 'Beverage',
  stars: 4.0,
  tags: ['Exotic', 'Healthy', 'organic', 'alchohol', 'brooklyn']
  },
  {name: 'Coconut Kombucha',
  brand: 'GT',
  price: 4.99,
  photo: '/photography/kombucha.jpg',
  totalSales: 46,
  category: 'Beverage',
  stars: 4.0,
  tags: ['Exotic', 'Healthy', 'organic','alchohol', 'brooklyn']
  },
  {name: 'Cranberry Kombucha',
  brand: 'GT',
  price: 4.99,
  photo: '/photography/kombucha.jpg',
  totalSales: 46,
  category: 'Beverage',
  stars: 4.0,
  tags: ['berry', 'Healthy', 'organic','alchohol', 'brooklyn']
  },
  {name: 'Sea Cucumber',
  brand: 'New Jersey Farms',
  price: 5.99,
  totalSales: 46,
  category: 'Seafood',
  stars: 4.0,
  tags: ['exotic', 'Healthy', 'seafood','fish', 'brooklyn']
  },
  {name: 'Gold-Plated Cucumber',
  brand: 'GT',
  price: 5.99,
  totalSales: 46,
  category: 'Cucu',
  stars: 4.0,
  tags: ['exotic', 'cucumber', 'gold', 'expensive']
  },
];

Products.bulkCreate(ourSeed)
.catch(console.error.bind(console))
.finally(_ => {
  db.close()
  console.log('Closed connection.')
  return null
})
